CREATE DATABASE [PersonDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PersonDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PersonDb.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PersonDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PersonDb_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [PersonDb] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [PersonDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PersonDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PersonDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PersonDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PersonDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [PersonDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PersonDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PersonDb] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [PersonDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PersonDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PersonDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PersonDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PersonDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PersonDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PersonDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PersonDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PersonDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PersonDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PersonDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PersonDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PersonDb] SET  READ_WRITE 
GO
ALTER DATABASE [PersonDb] SET RECOVERY FULL 
GO
ALTER DATABASE [PersonDb] SET  MULTI_USER 
GO
ALTER DATABASE [PersonDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PersonDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PersonDb] SET DELAYED_DURABILITY = DISABLED 
GO
USE [PersonDb]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [PersonDb]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [PersonDb] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

CREATE TABLE [dbo].[PERSON]
(
    [ID]	    BIGINT        NOT NULL IDENTITY (1, 1)
  , [FIRST_NAME]    NVARCHAR (64) NOT NULL
  , [MIDDLE_NAME]   NVARCHAR (64)     NULL
  , [LAST_NAME]	    NVARCHAR (64)     NULL
  , [DATE_OF_BIRTH] DATE		  NOT NULL
  , CONSTRAINT PK_PERSON_ID PRIMARY KEY ([ID])
);
GO

INSERT INTO [dbo].[PERSON] ([FIRST_NAME], [MIDDLE_NAME], [LAST_NAME], [DATE_OF_BIRTH])
VALUES (N'John', N'Edward', N'Doe', N'1990-08-14')
